### ISSUE TITLE
i added bun

### ISSUE THREAD

**Issue by BSN4** [silverwind/fetch-bench#1]
I added bun results were:

1- deno: 5523ms
2- bun: 6404ms
3- node-fetch: 7218ms
4- undici: 7437ms
5- axios: 10221ms

**Comment by silverwind** [comment]
Feel free to send a PR that adds `bun.js` and calls it in the Makefile.

**Comment by silverwind** [comment]
I'm getting strange zlib errors, any ideas:

```
$ bun run bun.js
Zlib error
Zlib error
Zlib error
ZlibError: fetch() failed
 path: "https://registry.npmjs.org/@babel%2fplugin-transform-literals"

**Comment by silverwind** [comment]
Ah, it's some bug in bun 0.2.1 that I was using, now works after upgrading to bun 0.5.0.

**Comment by silverwind** [comment]
Results from me:

```
$ make bench
axios: 2515ms
node-fetch: 4812ms
undici: 2868ms
deno: 2244ms
bun: 2730ms
```

**Comment by BSN4** [comment]
strange I'm on mac m1 pro

whats your platform

**Comment by silverwind** [comment]
Intel Macbook Air. Results vary of course but bun seems to be consistently slightly slow than deno for me.

**Comment by BSN4** [comment]
yeah same axios was the slowest also undici this on arm cpu.. most of our code will run in server eventually I think i'll just focus on the x86 results

**Comment by BSN4** [comment]
thanks for your great benchmark suite i think i should update to undici

**Comment by silverwind** [comment]
I've update undici to latest release.

**Comment by BSN4** [comment]
```bash

❯ make        
axios: 16406ms
node-fetch: 6696ms
undici: 5420ms
deno: 5005ms
bun: 6670ms
```
