### ISSUE TITLE
Problem in the warmup code

### ISSUE THREAD

**Issue by victor-homyakov** [silverwind/fetch-bench#3]
The warmup code in axios.js, bun.js and other similar files contains non-working `await`. E.g. code from https://github.com/silverwind/fetch-bench/blob/master/bun.js#L11

```js
await warmupUrls.map(url => fetch(url).then(res => res.text()));
```

Here we are actually awaiting for the array of promises, i.e. we don't wait at all. I think the valid code should look like

```js
await Promise.all(warmupUrls.map(url => fetch(url).then(res => res.text())));
```

The same error is in all benchmark files:
- https://github.com/silverwind/fetch-bench/blob/master/axios.js#L12
- https://github.com/silverwind/fetch-bench/blob/master/bun.js#L11
- https://github.com/silverwind/fetch-bench/blob/master/deno.js#L10
- https://github.com/silverwind/fetch-bench/blob/master/got.js#L12
- https://github.com/silverwind/fetch-bench/blob/master/nodefetch.js#L12
- https://github.com/silverwind/fetch-bench/blob/master/undici.js#L12

**Comment by silverwind** [comment]
Good find, it need to extract such common code to another file. Not sure if the warmup is actually giving any noticeable effect, maybe it can be dropped entirely.

**Comment by victor-homyakov** [comment]
> extract such common code to another file

https://github.com/victor-homyakov/fetch-bench/commit/aa67b6cd4fac7165332b3a941fabd6d304233d92

> Not sure if the warmup is actually giving any noticeable effect, maybe it can be dropped entirely.

It depends on your CPU and network speed. On slow networks, this benchmark most of the time awaits the incoming data. On a fast network and slow CPU, data processing time may be the bottleneck and warmup may help.

**Comment by silverwind** [comment]
Fixed with https://github.com/silverwind/fetch-bench/commit/df34b9bfe4285600b4261bd1154690e616869252.
